# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Jarvi10(object):
    def setupUi(self, Jarvi10):
        Jarvi10.setObjectName("Jarvi10")
        Jarvi10.resize(638, 480)
        self.centralwidget = QtWidgets.QWidget(Jarvi10)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 661, 501))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".ASSETS/MImN.gif"))
        self.label.setScaledContents(True)
        self.label.setOpenExternalLinks(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 10, 111, 191))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(".ASSETS/QjoV.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 410, 56, 17))
        self.pushButton.setStyleSheet("background-color: rgb(10, 10, 10);\n"
"font: 87 8pt \"Arial Black\";\n"
"background-color: rgb(151, 167, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 410, 56, 17))
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("background-color: rgb(219, 0, 0);\n"
"font: 87 8pt \"Arial Black\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(390, 10, 121, 31))
        self.textBrowser.setStyleSheet("background:transperent;\n"
"border-radius:none;\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(470, 80, 121, 31))
        self.textBrowser_2.setStyleSheet("background:transperent;\n"
"border-radius:none;\n"
"")
        self.textBrowser_2.setObjectName("textBrowser_2")
        Jarvi10.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Jarvi10)
        self.statusbar.setObjectName("statusbar")
        Jarvi10.setStatusBar(self.statusbar)

        self.retranslateUi(Jarvi10)
        QtCore.QMetaObject.connectSlotsByName(Jarvi10)

    def retranslateUi(self, Jarvi10):
        _translate = QtCore.QCoreApplication.translate
        Jarvi10.setWindowTitle(_translate("Jarvi10", "MainWindow"))
        self.pushButton.setText(_translate("Jarvi10", "Run"))
        self.pushButton_2.setText(_translate("Jarvi10", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Jarvi10 = QtWidgets.QMainWindow()
    ui = Ui_Jarvi10()
    ui.setupUi(Jarvi10)
    Jarvi10.show()
    sys.exit(app.exec_())
